version: 2
updates:
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "04:00"
    timezone: "Europe/Amsterdam"
  open-pull-requests-limit: 25
  target-branch: master
  assignees:
    - "mprins"
  reviewers:
    - "mprins"
