version: 2
updates:
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
    time: "17:00"
    timezone: "Europe/Amsterdam"
  open-pull-requests-limit: 25
  target-branch: main
  assignees:
    - "mprins"
  reviewers:
    - "mprins"

version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
  - build-infra
  assignees:
    - "mprins"
  reviewers:
    - "mprins"
